name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
        swiftmailer-version: ['4.1.3', '^4', '5.0.0', '^5', '6.0.0', '^6']
        exclude:
          - php-version: '5.6'
            swiftmailer-version: '6.0.0'
          - php-version: '5.6'
            swiftmailer-version: '^6'
        include:
          - php-version: '7.0'
            swiftmailer-version: '^6'
            report-coverage: true
    name: PHP ${{ matrix.php-version }}, Swift Mailer ${{ matrix.swiftmailer-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@1.4.4
        with:
          php-version: ${{ matrix.php-version }}
          extension-csv: dom, mbstring
      - name: Install dependencies
        run: |
          composer require "swiftmailer/swiftmailer ${{ matrix.swiftmailer-version }}" --no-update
          if [[ ${{ matrix.php-version }} > 7.1 ]]
            then composer require "phpunit/phpunit >=6.0 <8" --dev --no-update
          fi
          composer install
      - name: Test and publish code coverage
        if: matrix.report-coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          # Get it on https://codeclimate.com/repos/{repo id}/settings/test_reporter
          CC_TEST_REPORTER_ID: 23c7ee088614ba3aa3c7b2e8feaaa80cede3c8e4c04bafcde1d9cb0359f5b8c3
        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: php vendor/bin/phpunit --coverage-text --coverage-clover ./clover.xml
          debug: true
      - name: Test
        if: "!matrix.report-coverage"
        run: php vendor/bin/phpunit --coverage-text
